version: '3.8'

services:
  database: 
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hmg
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - '5432:5432'
volumes:
  postgres: